name: ddns
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.1
  json_annotation: ^4.0.1
  logger: ^1.0.0
  args: ^2.0.0
  path: ^1.8.0
  event_bus: ^2.0.0
  mailer: ^5.0.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
  json_serializable: ^4.1.0
  build_runner: 1.12.2
