name: ddns
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.1.2
  json_annotation: ^4.8.1
  logger: ^2.0.2
  args: ^2.4.2
  path: ^1.9.0
  event_bus: ^2.0.0
  mailer: ^6.0.1

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.25.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.8
